package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

//easyjson:json
type UserUpdate struct {
	About    string       `json:"about,omitempty"`
	Email    strfmt.Email `json:"email,omitempty"`
	Fullname string       `json:"fullname,omitempty"`
}
